// Part 3: Services branches
module.exports = [
    {
        name: 'feature/stacks-service',
        prTitle: 'feat: implement Stacks blockchain interaction service',
        prBody: 'Creates a centralized service layer for interacting with the Stacks blockchain. Wraps @stacks/transactions for building contract calls, STX transfers, and reading contract state. Also handles post-condition construction and transaction broadcasting. This module is used by all components that need to read from or write to the chain.',
        commits: [
            { file: 'src/services/stacksService.js', mode: 'create', content: '// Stacks blockchain interaction service\n// Wraps @stacks/transactions and @stacks/connect\n\n', msg: 'feat: create stacks service file with description' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'import {\n  makeSTXTokenTransfer,\n  makeContractCall,\n  callReadOnlyFunction,\n  broadcastTransaction,\n  AnchorMode,\n  PostConditionMode,\n  uintCV,\n  principalCV,\n  standardPrincipalCV,\n  bufferCVFromString,\n} from \'@stacks/transactions\';\n\n', msg: 'feat: import stacks transactions SDK functions' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'import { openSTXTransfer, openContractCall } from \'@stacks/connect\';\nimport { DEFAULT_NETWORK, API_URL } from \'../config/network.js\';\n\n', msg: 'feat: import stacks connect and network config' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'const CONTRACT_ADDRESS = process.env.DEPLOYER_ADDRESS || \'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM\';\nconst CONTRACT_NAME = \'tipjar\';\n\n', msg: 'feat: define contract address and name constants' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'export async function sendTip(recipientAddress, amountInMicroStx) {\n  const options = {\n    recipient: recipientAddress,\n    amount: amountInMicroStx,\n    memo: \'Tip via Tipjar\',\n    network: DEFAULT_NETWORK,\n    anchorMode: AnchorMode.Any,\n    onFinish: (data) => {\n      console.log(\'Transaction submitted:\', data.txId);\n      return data;\n    },\n  };\n  return openSTXTransfer(options);\n}\n\n', msg: 'feat: implement sendTip function using stacks connect' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'export async function registerCreator(name, description, category) {\n  const options = {\n    network: DEFAULT_NETWORK,\n    anchorMode: AnchorMode.Any,\n    contractAddress: CONTRACT_ADDRESS,\n    contractName: \'tip-registry\',\n    functionName: \'register\',\n    functionArgs: [\n      bufferCVFromString(name),\n      bufferCVFromString(description),\n      bufferCVFromString(category),\n    ],\n    postConditionMode: PostConditionMode.Deny,\n    postConditions: [],\n    onFinish: (data) => console.log(\'Registered:\', data.txId),\n  };\n  return openContractCall(options);\n}\n\n', msg: 'feat: implement creator registration contract call' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'export async function getTipAmount(sender, recipient) {\n  const result = await callReadOnlyFunction({\n    network: DEFAULT_NETWORK,\n    contractAddress: CONTRACT_ADDRESS,\n    contractName: CONTRACT_NAME,\n    functionName: \'get-tip\',\n    functionArgs: [standardPrincipalCV(sender), standardPrincipalCV(recipient)],\n    senderAddress: sender,\n  });\n  return result;\n}\n\n', msg: 'feat: add read-only tip amount query function' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'export async function getPlatformStats() {\n  const totalTips = await callReadOnlyFunction({\n    network: DEFAULT_NETWORK,\n    contractAddress: CONTRACT_ADDRESS,\n    contractName: CONTRACT_NAME,\n    functionName: \'get-total-tips\',\n    functionArgs: [],\n    senderAddress: CONTRACT_ADDRESS,\n  });\n  const tipCount = await callReadOnlyFunction({\n    network: DEFAULT_NETWORK,\n    contractAddress: CONTRACT_ADDRESS,\n    contractName: CONTRACT_NAME,\n    functionName: \'get-tip-count\',\n    functionArgs: [],\n    senderAddress: CONTRACT_ADDRESS,\n  });\n  return { totalTips, tipCount };\n}\n\n', msg: 'feat: implement platform stats aggregation query' },
            { file: 'src/services/stacksService.js', mode: 'append', content: 'export async function fetchAccountBalance(address) {\n  const response = await fetch(`${API_URL}/extended/v1/address/${address}/balances`);\n  const data = await response.json();\n  return data.stx?.balance || \'0\';\n}\n', msg: 'feat: add account STX balance fetcher via Hiro API' },
        ]
    },
    {
        name: 'feature/walletconnect-service',
        prTitle: 'feat: build WalletConnect integration service for multi-wallet support',
        prBody: 'Implements the WalletConnect service that manages session lifecycle using @walletconnect/sign-client. Handles initialization, session proposal, approval/rejection, and disconnection. The service exposes methods for requesting STX transfers and contract calls through connected wallets, extending the platform beyond just Hiro Wallet.',
        commits: [
            { file: 'src/services/walletConnectService.js', mode: 'create', content: '// WalletConnect integration service\n// Multi-wallet support via WalletConnect protocol\n\n', msg: 'feat: create walletconnect service file' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'import SignClient from \'@walletconnect/sign-client\';\nimport { WalletConnectModal } from \'@walletconnect/modal\';\nimport { WC_PROJECT_ID, WC_METADATA, WC_REQUIRED_NAMESPACES } from \'../config/walletConnect.js\';\n\n', msg: 'feat: import walletconnect packages and config' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'let signClient = null;\nlet currentSession = null;\nlet walletConnectModal = null;\n\n', msg: 'feat: declare module-level state variables' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'export async function initWalletConnect() {\n  signClient = await SignClient.init({\n    projectId: WC_PROJECT_ID,\n    metadata: WC_METADATA,\n  });\n\n  walletConnectModal = new WalletConnectModal({\n    projectId: WC_PROJECT_ID,\n    chains: [\'stacks:1\'],\n  });\n\n  setupEventListeners();\n  return signClient;\n}\n\n', msg: 'feat: implement WalletConnect client initialization' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'function setupEventListeners() {\n  signClient.on(\'session_event\', ({ event }) => {\n    console.log(\'Session event:\', event);\n  });\n\n  signClient.on(\'session_update\', ({ topic, params }) => {\n    const { namespaces } = params;\n    const session = signClient.session.get(topic);\n    currentSession = { ...session, namespaces };\n  });\n\n  signClient.on(\'session_delete\', () => {\n    console.log(\'Session deleted\');\n    currentSession = null;\n  });\n}\n\n', msg: 'feat: add WalletConnect session event listeners' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'export async function connectWallet() {\n  const { uri, approval } = await signClient.connect({\n    requiredNamespaces: WC_REQUIRED_NAMESPACES,\n  });\n\n  if (uri) {\n    walletConnectModal.openModal({ uri });\n  }\n\n  currentSession = await approval();\n  walletConnectModal.closeModal();\n  return currentSession;\n}\n\n', msg: 'feat: implement wallet connection flow with modal' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'export async function disconnectWallet() {\n  if (currentSession) {\n    await signClient.disconnect({\n      topic: currentSession.topic,\n      reason: { code: 6000, message: \'User disconnected\' },\n    });\n    currentSession = null;\n  }\n}\n\n', msg: 'feat: implement wallet disconnection handler' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'export async function requestStxTransfer(recipient, amount) {\n  if (!currentSession) throw new Error(\'No active session\');\n  const result = await signClient.request({\n    topic: currentSession.topic,\n    chainId: \'stacks:1\',\n    request: {\n      method: \'stacks_stxTransfer\',\n      params: { recipient, amount: amount.toString() },\n    },\n  });\n  return result;\n}\n\n', msg: 'feat: add STX transfer request via WalletConnect' },
            { file: 'src/services/walletConnectService.js', mode: 'append', content: 'export function getSession() {\n  return currentSession;\n}\n\nexport function isConnected() {\n  return currentSession !== null;\n}\n', msg: 'feat: add session getter and connection status check' },
        ]
    },
    {
        name: 'feature/chainhooks-service',
        prTitle: 'feat: integrate Chainhooks client for real-time on-chain event monitoring',
        prBody: 'Adds the chainhooks service that uses @hirosystems/chainhooks-client to register and manage webhooks for on-chain events. Monitors STX transfers and contract calls related to the tipjar contracts. When a tip transaction is confirmed, the webhook triggers notification and stats updates in real time.',
        commits: [
            { file: 'src/services/chainhooksService.js', mode: 'create', content: '// Chainhooks integration service\n// Real-time on-chain event monitoring via @hirosystems/chainhooks-client\n\n', msg: 'feat: create chainhooks service file' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'import Chainhook from \'@hirosystems/chainhooks-client\';\n\n', msg: 'feat: import chainhooks client package' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'const CHAINHOOKS_API_KEY = process.env.CHAINHOOKS_API_KEY || \'\';\nconst WEBHOOK_URL = process.env.CHAINHOOKS_WEBHOOK_URL || \'http://localhost:3001/webhooks\';\n\nlet chainhooksClient = null;\n\n', msg: 'feat: configure chainhooks client credentials' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export async function initChainhooks() {\n  chainhooksClient = new Chainhook({\n    apiKey: CHAINHOOKS_API_KEY,\n  });\n  console.log(\'Chainhooks client initialized\');\n  return chainhooksClient;\n}\n\n', msg: 'feat: implement chainhooks client initialization' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export async function registerTipWebhook(contractAddress, contractName) {\n  const webhook = await chainhooksClient.createHook({\n    name: \'tip-monitor\',\n    version: 1,\n    chain: \'stacks\',\n    networks: { testnet: { if_this: { scope: \'contract_call\', contract_identifier: `${contractAddress}.${contractName}`, method: \'send-tip\' }, then_that: { http_post: { url: WEBHOOK_URL, authorization_header: \'Bearer webhook-secret\' } } } },\n  });\n  console.log(\'Webhook registered:\', webhook);\n  return webhook;\n}\n\n', msg: 'feat: register webhook for send-tip contract calls' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export async function registerTransferWebhook() {\n  const webhook = await chainhooksClient.createHook({\n    name: \'stx-transfer-monitor\',\n    version: 1,\n    chain: \'stacks\',\n    networks: { testnet: { if_this: { scope: \'stx_event\', actions: [\'transfer\'] }, then_that: { http_post: { url: `${WEBHOOK_URL}/transfers`, authorization_header: \'Bearer webhook-secret\' } } } },\n  });\n  return webhook;\n}\n\n', msg: 'feat: register webhook for STX transfer events' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export async function listWebhooks() {\n  if (!chainhooksClient) throw new Error(\'Chainhooks not initialized\');\n  return chainhooksClient.listHooks();\n}\n\n', msg: 'feat: add webhook listing utility function' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export async function deleteWebhook(hookId) {\n  if (!chainhooksClient) throw new Error(\'Chainhooks not initialized\');\n  return chainhooksClient.deleteHook(hookId);\n}\n\n', msg: 'feat: add webhook deletion function' },
            { file: 'src/services/chainhooksService.js', mode: 'append', content: 'export function handleWebhookPayload(payload) {\n  const { apply } = payload;\n  if (apply && apply.length > 0) {\n    for (const block of apply) {\n      for (const tx of block.transactions) {\n        console.log(\'Tip transaction detected:\', tx.transaction_identifier);\n      }\n    }\n  }\n  return apply;\n}\n', msg: 'feat: implement webhook payload processing handler' },
        ]
    },
    {
        name: 'feature/tip-service',
        prTitle: 'feat: create tip orchestration service with history and analytics',
        prBody: 'Builds the tip service that orchestrates the full tipping flow — validating inputs, calling the Stacks service for on-chain transfers, and recording tips in local state for fast UI rendering. Also provides methods for fetching tip history and computing analytics like top tippers and most-tipped creators.',
        commits: [
            { file: 'src/services/tipService.js', mode: 'create', content: '// Tip orchestration service\n// Manages tipping flow, history, and analytics\n\n', msg: 'feat: create tip service file' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'import { sendTip as stacksSendTip, getTipAmount } from \'./stacksService.js\';\n\n', msg: 'feat: import stacks service functions' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'const tipHistory = [];\nconst TIP_MIN = 1000; // 0.001 STX in micro-STX\nconst TIP_MAX = 100000000; // 100 STX\n\n', msg: 'feat: define tip history store and limits' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'export function validateTip(amount, recipient) {\n  if (!recipient || recipient.length < 30) return { valid: false, error: \'Invalid recipient address\' };\n  if (amount < TIP_MIN) return { valid: false, error: `Minimum tip is ${TIP_MIN / 1000000} STX` };\n  if (amount > TIP_MAX) return { valid: false, error: `Maximum tip is ${TIP_MAX / 1000000} STX` };\n  return { valid: true, error: null };\n}\n\n', msg: 'feat: implement tip amount and recipient validation' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'export async function processTip(recipient, amount, memo = \'\') {\n  const validation = validateTip(amount, recipient);\n  if (!validation.valid) throw new Error(validation.error);\n\n  const result = await stacksSendTip(recipient, amount.toString());\n\n  const tipRecord = {\n    id: Date.now().toString(36),\n    recipient,\n    amount,\n    memo,\n    timestamp: new Date().toISOString(),\n    txId: result?.txId || null,\n    status: \'pending\',\n  };\n\n  tipHistory.push(tipRecord);\n  return tipRecord;\n}\n\n', msg: 'feat: implement tip processing with validation and recording' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'export function getTipHistory() {\n  return [...tipHistory].reverse();\n}\n\n', msg: 'feat: add reverse-chronological tip history getter' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'export function getTipStats() {\n  const totalAmount = tipHistory.reduce((sum, tip) => sum + tip.amount, 0);\n  const uniqueRecipients = new Set(tipHistory.map(t => t.recipient)).size;\n  return {\n    totalTips: tipHistory.length,\n    totalAmount,\n    uniqueRecipients,\n    averageTip: tipHistory.length > 0 ? totalAmount / tipHistory.length : 0,\n  };\n}\n\n', msg: 'feat: implement tip statistics computation' },
            { file: 'src/services/tipService.js', mode: 'append', content: 'export function getTopRecipients(limit = 5) {\n  const recipientMap = {};\n  tipHistory.forEach(tip => {\n    if (!recipientMap[tip.recipient]) recipientMap[tip.recipient] = 0;\n    recipientMap[tip.recipient] += tip.amount;\n  });\n  return Object.entries(recipientMap)\n    .sort(([,a], [,b]) => b - a)\n    .slice(0, limit)\n    .map(([address, total]) => ({ address, total }));\n}\n', msg: 'feat: add top recipients leaderboard query' },
        ]
    },
    {
        name: 'feature/auth-service',
        prTitle: 'feat: implement authentication service with Stacks session management',
        prBody: 'Creates the auth service that wraps @stacks/connect for authentication lifecycle. Manages AppConfig, UserSession creation, login via showConnect, logout, and session persistence. Components use this service to check if a user is authenticated and to get profile information like the STX address.',
        commits: [
            { file: 'src/services/authService.js', mode: 'create', content: '// Authentication service\n// Session management using @stacks/connect\n\n', msg: 'feat: create authentication service file' },
            { file: 'src/services/authService.js', mode: 'append', content: 'import { AppConfig, UserSession, showConnect } from \'@stacks/connect\';\n\n', msg: 'feat: import stacks connect auth modules' },
            { file: 'src/services/authService.js', mode: 'append', content: 'const appConfig = new AppConfig([\'store_write\', \'publish_data\']);\nconst userSession = new UserSession({ appConfig });\n\n', msg: 'feat: initialize app config and user session' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export function authenticate() {\n  showConnect({\n    appDetails: {\n      name: \'Tipjar\',\n      icon: window.location.origin + \'/logo.png\',\n    },\n    redirectTo: \'/\',\n    onFinish: () => {\n      window.location.reload();\n    },\n    userSession,\n  });\n}\n\n', msg: 'feat: implement authenticate function with showConnect' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export function logout() {\n  userSession.signUserOut(window.location.origin);\n}\n\n', msg: 'feat: implement logout with session cleanup' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export function isAuthenticated() {\n  return userSession.isUserSignedIn();\n}\n\n', msg: 'feat: add authentication status check function' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export function getUserData() {\n  if (!isAuthenticated()) return null;\n  return userSession.loadUserData();\n}\n\n', msg: 'feat: add user data retrieval function' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export function getStxAddress() {\n  const userData = getUserData();\n  if (!userData) return null;\n  return userData.profile?.stxAddress?.testnet || userData.profile?.stxAddress?.mainnet || null;\n}\n\n', msg: 'feat: extract STX address from user profile' },
            { file: 'src/services/authService.js', mode: 'append', content: 'export { userSession };\n', msg: 'feat: export userSession instance for external use' },
        ]
    },
    {
        name: 'feature/notification-service',
        prTitle: 'feat: add notification service for tip event alerts',
        prBody: 'Implements a lightweight notification service that provides in-app toast notifications when tips are sent, received, or when transactions confirm. Uses an observer pattern so that multiple UI components can subscribe to notification events without tight coupling.',
        commits: [
            { file: 'src/services/notificationService.js', mode: 'create', content: '// Notification service\n// Observable toast notification system\n\n', msg: 'feat: create notification service file' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'const listeners = [];\nconst notificationQueue = [];\nconst MAX_QUEUE_SIZE = 50;\n\n', msg: 'feat: define notification state and queue limits' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function subscribe(callback) {\n  listeners.push(callback);\n  return () => {\n    const index = listeners.indexOf(callback);\n    if (index > -1) listeners.splice(index, 1);\n  };\n}\n\n', msg: 'feat: implement subscribe function with unsubscribe return' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'function notify(notification) {\n  notificationQueue.push(notification);\n  if (notificationQueue.length > MAX_QUEUE_SIZE) notificationQueue.shift();\n  listeners.forEach(cb => cb(notification));\n}\n\n', msg: 'feat: add internal notify dispatch function' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function tipSent(recipient, amount) {\n  notify({ type: \'success\', title: \'Tip Sent!\', message: `You sent ${amount / 1000000} STX to ${recipient.slice(0, 8)}...`, timestamp: Date.now() });\n}\n\n', msg: 'feat: add tipSent notification emitter' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function tipReceived(sender, amount) {\n  notify({ type: \'info\', title: \'Tip Received!\', message: `${sender.slice(0, 8)}... sent you ${amount / 1000000} STX`, timestamp: Date.now() });\n}\n\n', msg: 'feat: add tipReceived notification emitter' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function transactionConfirmed(txId) {\n  notify({ type: \'success\', title: \'Transaction Confirmed\', message: `TX ${txId.slice(0, 10)}... confirmed on-chain`, timestamp: Date.now() });\n}\n\n', msg: 'feat: add transaction confirmation notification' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function errorOccurred(message) {\n  notify({ type: \'error\', title: \'Error\', message, timestamp: Date.now() });\n}\n\n', msg: 'feat: add error notification emitter' },
            { file: 'src/services/notificationService.js', mode: 'append', content: 'export function getNotificationHistory() {\n  return [...notificationQueue];\n}\n', msg: 'feat: add notification history getter' },
        ]
    },
];
