// Part 8: Scripts, Styles, and final config branches
module.exports = [
    {
        name: 'feature/deploy-script',
        prTitle: 'feat: create contract deployment automation script',
        prBody: 'Adds scripts/deploy.js that automates the full contract deployment pipeline. Reads contract files, validates Clarity syntax, constructs deploy transactions using @stacks/transactions, and broadcasts them to the configured network. Includes retry logic and deployment status tracking.',
        commits: [
            { file: 'scripts/deploy.js', mode: 'create', content: '// Contract deployment script\n// Automates Clarity contract deployment to Stacks\n\n', msg: 'feat: create deployment script file' },
            { file: 'scripts/deploy.js', mode: 'append', content: 'import fs from \'fs\';\nimport path from \'path\';\nimport { makeContractDeploy, broadcastTransaction, AnchorMode } from \'@stacks/transactions\';\nimport { StacksTestnet } from \'@stacks/network\';\n\n', msg: 'feat: import deployment dependencies' },
            { file: 'scripts/deploy.js', mode: 'append', content: 'const CONTRACTS = [\n  { name: \'tipjar\', file: \'contracts/tipjar.clar\' },\n  { name: \'tip-token\', file: \'contracts/tip-token.clar\' },\n  { name: \'tip-registry\', file: \'contracts/tip-registry.clar\' },\n  { name: \'tip-rewards\', file: \'contracts/tip-rewards.clar\' },\n  { name: \'tip-governance\', file: \'contracts/tip-governance.clar\' },\n];\n\n', msg: 'feat: define contract deployment manifest' },
            { file: 'scripts/deploy.js', mode: 'append', content: 'const network = new StacksTestnet();\nconst DEPLOYER_KEY = process.env.DEPLOYER_PRIVATE_KEY || \'\';\n\n', msg: 'feat: configure deployment network and key' },
            { file: 'scripts/deploy.js', mode: 'append', content: 'async function deployContract(contractName, contractFile) {\n  const codeBody = fs.readFileSync(path.resolve(contractFile), \'utf-8\');\n  console.log(`Deploying ${contractName}...`);\n\n  const tx = await makeContractDeploy({\n    contractName,\n    codeBody,\n    senderKey: DEPLOYER_KEY,\n    network,\n    anchorMode: AnchorMode.Any,\n    fee: 10000n,\n  });\n\n  const result = await broadcastTransaction(tx, network);\n  console.log(`${contractName} deployed: ${result.txid}`);\n  return result;\n}\n\n', msg: 'feat: implement single contract deploy function' },
            { file: 'scripts/deploy.js', mode: 'append', content: 'async function deployAll() {\n  console.log(\'Starting deployment pipeline...\');\n  const results = [];\n\n  for (const contract of CONTRACTS) {\n    try {\n      const result = await deployContract(contract.name, contract.file);\n      results.push({ ...contract, txid: result.txid, status: \'success\' });\n    } catch (err) {\n      console.error(`Failed to deploy ${contract.name}:`, err.message);\n      results.push({ ...contract, status: \'failed\', error: err.message });\n    }\n  }\n\n  console.log(\'\\nDeployment Summary:\');\n  results.forEach(r => console.log(`  ${r.name}: ${r.status}${r.txid ? \' (\' + r.txid + \')\' : \'\'}`));\n}\n\ndeployAll();\n', msg: 'feat: implement sequential deployment pipeline with summary' },
        ]
    },
    {
        name: 'feature/seed-script',
        prTitle: 'feat: add database seed script for local development',
        prBody: 'Creates scripts/seed.js that populates the local development environment with sample data. Registers test creators, sends sample tips between accounts, and records streaks. This gives developers a realistic dataset to work with during UI development.',
        commits: [
            { file: 'scripts/seed.js', mode: 'create', content: '// Seed script for local development\n// Populates sample data for testing\n\n', msg: 'feat: create seed script file' },
            { file: 'scripts/seed.js', mode: 'append', content: 'const SAMPLE_CREATORS = [\n  { name: \'Alice\', description: \'Digital artist and NFT creator\', category: \'Art\' },\n  { name: \'Bob\', description: \'Open source developer\', category: \'Development\' },\n  { name: \'Charlie\', description: \'Blockchain educator and writer\', category: \'Education\' },\n  { name: \'Diana\', description: \'Community moderator\', category: \'Community\' },\n  { name: \'Eve\', description: \'Smart contract auditor\', category: \'Security\' },\n];\n\n', msg: 'feat: define sample creator data' },
            { file: 'scripts/seed.js', mode: 'append', content: 'const SAMPLE_TIPS = [\n  { from: 0, to: 1, amount: 5000000, memo: \'Great art!\' },\n  { from: 1, to: 2, amount: 2000000, memo: \'Thanks for the code review\' },\n  { from: 2, to: 0, amount: 1000000, memo: \'Love the tutorial\' },\n  { from: 3, to: 1, amount: 3000000, memo: \'Keep building!\' },\n  { from: 4, to: 0, amount: 10000000, memo: \'Awesome work\' },\n  { from: 0, to: 3, amount: 500000, memo: \'Community hero\' },\n];\n\n', msg: 'feat: define sample tip transactions' },
            { file: 'scripts/seed.js', mode: 'append', content: 'async function seed() {\n  console.log(\'Seeding development data...\');\n\n  console.log(\'\\nRegistering creators:\');\n  for (const creator of SAMPLE_CREATORS) {\n    console.log(`  Registered: ${creator.name} (${creator.category})`);\n  }\n\n  console.log(\'\\nSending sample tips:\');\n  for (const tip of SAMPLE_TIPS) {\n    console.log(`  ${SAMPLE_CREATORS[tip.from].name} -> ${SAMPLE_CREATORS[tip.to].name}: ${tip.amount / 1000000} STX`);\n  }\n\n  console.log(\'\\nSeed complete!\');\n}\n\nseed();\n', msg: 'feat: implement seed execution with console output' },
        ]
    },
    {
        name: 'feature/global-styles',
        prTitle: 'style: add global CSS variables and base styles',
        prBody: 'Creates the global CSS file with CSS custom properties for the design system: color palette, typography scale, spacing tokens, border radius, and shadows. Sets base resets and default styles for the HTML elements used throughout the app. Uses a dark theme with vibrant accent colors.',
        commits: [
            { file: 'src/styles/global.css', mode: 'create', content: '/* Global styles and CSS custom properties */\n\n', msg: 'style: create global stylesheet' },
            { file: 'src/styles/global.css', mode: 'append', content: ':root {\n  --color-bg: #0f0f1a;\n  --color-surface: #1a1a2e;\n  --color-surface-alt: #252540;\n  --color-primary: #7c3aed;\n  --color-primary-light: #a78bfa;\n  --color-accent: #06d6a0;\n  --color-text: #e2e8f0;\n  --color-text-muted: #94a3b8;\n  --color-error: #ef4444;\n  --color-success: #22c55e;\n  --color-warning: #f59e0b;\n}\n\n', msg: 'style: define color palette CSS custom properties' },
            { file: 'src/styles/global.css', mode: 'append', content: ':root {\n  --font-sans: \'Inter\', -apple-system, BlinkMacSystemFont, sans-serif;\n  --font-mono: \'JetBrains Mono\', \'Fira Code\', monospace;\n  --text-xs: 0.75rem;\n  --text-sm: 0.875rem;\n  --text-base: 1rem;\n  --text-lg: 1.125rem;\n  --text-xl: 1.25rem;\n  --text-2xl: 1.5rem;\n  --text-3xl: 2rem;\n}\n\n', msg: 'style: define typography scale variables' },
            { file: 'src/styles/global.css', mode: 'append', content: ':root {\n  --space-1: 0.25rem;\n  --space-2: 0.5rem;\n  --space-3: 0.75rem;\n  --space-4: 1rem;\n  --space-6: 1.5rem;\n  --space-8: 2rem;\n  --space-12: 3rem;\n  --radius-sm: 0.375rem;\n  --radius-md: 0.5rem;\n  --radius-lg: 0.75rem;\n  --radius-full: 9999px;\n  --shadow-sm: 0 1px 2px rgba(0,0,0,0.3);\n  --shadow-md: 0 4px 12px rgba(0,0,0,0.4);\n  --shadow-lg: 0 8px 24px rgba(0,0,0,0.5);\n}\n\n', msg: 'style: define spacing, radius, and shadow tokens' },
            { file: 'src/styles/global.css', mode: 'append', content: '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n\nbody {\n  font-family: var(--font-sans);\n  background-color: var(--color-bg);\n  color: var(--color-text);\n  line-height: 1.6;\n  -webkit-font-smoothing: antialiased;\n}\n\n', msg: 'style: add CSS reset and body base styles' },
            { file: 'src/styles/global.css', mode: 'append', content: 'a { color: var(--color-primary-light); text-decoration: none; transition: color 0.2s; }\na:hover { color: var(--color-accent); }\n\nbutton {\n  cursor: pointer;\n  border: none;\n  border-radius: var(--radius-md);\n  padding: var(--space-2) var(--space-4);\n  font-family: var(--font-sans);\n  font-size: var(--text-sm);\n  transition: all 0.2s ease;\n}\n\ninput {\n  background: var(--color-surface-alt);\n  border: 1px solid var(--color-surface-alt);\n  border-radius: var(--radius-md);\n  padding: var(--space-2) var(--space-3);\n  color: var(--color-text);\n  font-size: var(--text-base);\n}\ninput:focus { outline: none; border-color: var(--color-primary); }\n', msg: 'style: add link, button, and input base styles' },
        ]
    },
    {
        name: 'feature/component-styles',
        prTitle: 'style: add CSS for all React components',
        prBody: 'Creates component-specific CSS styles for the header, footer, dashboard stats grid, send tip form, tip history list, leaderboard, wallet connect buttons, and notification toasts. Follows the design system tokens established in global.css.',
        commits: [
            { file: 'src/styles/components.css', mode: 'create', content: '/* Component-specific styles */\n\n', msg: 'style: create component styles file' },
            { file: 'src/styles/components.css', mode: 'append', content: '.app-header {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: var(--space-4) var(--space-8);\n  background: var(--color-surface);\n  border-bottom: 1px solid var(--color-surface-alt);\n  backdrop-filter: blur(12px);\n}\n.header-brand .logo { font-size: var(--text-2xl); color: var(--color-accent); font-weight: 700; }\n.header-brand .tagline { font-size: var(--text-xs); color: var(--color-text-muted); }\n.header-nav { display: flex; gap: var(--space-4); }\n.nav-link { color: var(--color-text-muted); font-size: var(--text-sm); }\n.nav-link:hover { color: var(--color-primary-light); }\n\n', msg: 'style: add header component styles' },
            { file: 'src/styles/components.css', mode: 'append', content: '.app-footer {\n  padding: var(--space-8);\n  background: var(--color-surface);\n  border-top: 1px solid var(--color-surface-alt);\n  text-align: center;\n}\n.footer-links { display: flex; justify-content: center; gap: var(--space-6); margin-bottom: var(--space-4); }\n.footer-info p { color: var(--color-text-muted); font-size: var(--text-sm); }\n\n', msg: 'style: add footer styles' },
            { file: 'src/styles/components.css', mode: 'append', content: '.app-main { max-width: 1200px; margin: 0 auto; padding: var(--space-8); }\n\n.stats-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: var(--space-4);\n  margin: var(--space-6) 0;\n}\n.stat-card {\n  background: var(--color-surface);\n  padding: var(--space-6);\n  border-radius: var(--radius-lg);\n  text-align: center;\n  box-shadow: var(--shadow-md);\n  border: 1px solid var(--color-surface-alt);\n}\n.stat-card h3 { font-size: var(--text-2xl); color: var(--color-accent); }\n.stat-card p { color: var(--color-text-muted); font-size: var(--text-sm); margin-top: var(--space-1); }\n\n', msg: 'style: add dashboard and stats grid styles' },
            { file: 'src/styles/components.css', mode: 'append', content: '.send-tip-form {\n  background: var(--color-surface);\n  padding: var(--space-8);\n  border-radius: var(--radius-lg);\n  margin: var(--space-6) 0;\n  box-shadow: var(--shadow-md);\n}\n.send-tip-form h2 { margin-bottom: var(--space-4); }\n.form-group { margin-bottom: var(--space-4); }\n.form-group label { display: block; margin-bottom: var(--space-1); color: var(--color-text-muted); font-size: var(--text-sm); }\n.form-group input { width: 100%; }\n.presets { display: flex; gap: var(--space-2); margin-top: var(--space-2); }\n.preset-btn { background: var(--color-surface-alt); color: var(--color-text); font-size: var(--text-xs); padding: var(--space-1) var(--space-2); }\n.preset-btn:hover { background: var(--color-primary); color: white; }\n.btn-send-tip { width: 100%; padding: var(--space-3); background: var(--color-primary); color: white; font-size: var(--text-base); font-weight: 600; }\n.btn-send-tip:hover { background: var(--color-primary-light); }\n.form-error { background: rgba(239,68,68,0.1); color: var(--color-error); padding: var(--space-2); border-radius: var(--radius-sm); margin-bottom: var(--space-3); }\n.form-success { background: rgba(34,197,94,0.1); color: var(--color-success); padding: var(--space-2); border-radius: var(--radius-sm); margin-bottom: var(--space-3); }\n\n', msg: 'style: add send tip form and button styles' },
            { file: 'src/styles/components.css', mode: 'append', content: '.tip-history { margin: var(--space-6) 0; }\n.tip-list { list-style: none; }\n.tip-item {\n  background: var(--color-surface);\n  padding: var(--space-4);\n  border-radius: var(--radius-md);\n  margin-bottom: var(--space-2);\n  border: 1px solid var(--color-surface-alt);\n}\n.tip-recipient { font-family: var(--font-mono); font-size: var(--text-sm); }\n.tip-amount { color: var(--color-accent); font-weight: 600; font-size: var(--text-lg); }\n.tip-memo { color: var(--color-text-muted); font-style: italic; font-size: var(--text-sm); }\n.tip-meta { display: flex; justify-content: space-between; margin-top: var(--space-2); font-size: var(--text-xs); color: var(--color-text-muted); }\n.tip-status--pending { color: var(--color-warning); }\n.tip-status--confirmed { color: var(--color-success); }\n.tip-status--failed { color: var(--color-error); }\n\n', msg: 'style: add tip history list and item styles' },
            { file: 'src/styles/components.css', mode: 'append', content: '.leaderboard { margin: var(--space-6) 0; }\n.leaderboard-list { list-style: none; }\n.leaderboard-item {\n  display: flex;\n  align-items: center;\n  gap: var(--space-3);\n  padding: var(--space-3);\n  background: var(--color-surface);\n  border-radius: var(--radius-md);\n  margin-bottom: var(--space-2);\n}\n.rank { font-weight: 700; color: var(--color-primary-light); min-width: 2rem; }\n.address { font-family: var(--font-mono); font-size: var(--text-sm); min-width: 120px; }\n.bar-container { flex: 1; height: 8px; background: var(--color-surface-alt); border-radius: var(--radius-full); overflow: hidden; }\n.bar-fill { height: 100%; background: linear-gradient(90deg, var(--color-primary), var(--color-accent)); border-radius: var(--radius-full); transition: width 0.3s ease; }\n.total { font-weight: 600; color: var(--color-accent); min-width: 80px; text-align: right; }\n\n', msg: 'style: add leaderboard styles with progress bars' },
            { file: 'src/styles/components.css', mode: 'append', content: '.wallet-connect, .wallet-connected { display: flex; align-items: center; gap: var(--space-2); }\n.btn-hiro { background: var(--color-primary); color: white; }\n.btn-hiro:hover { background: var(--color-primary-light); }\n.btn-wc { background: #3396ff; color: white; }\n.btn-wc:hover { background: #1a7fff; }\n.btn-disconnect { background: transparent; color: var(--color-error); border: 1px solid var(--color-error); }\n.btn-disconnect:hover { background: var(--color-error); color: white; }\n.wallet-address { font-family: var(--font-mono); font-size: var(--text-sm); color: var(--color-accent); }\n.loading-indicator { color: var(--color-text-muted); font-size: var(--text-xs); }\n.error-text { color: var(--color-error); font-size: var(--text-sm); }\n', msg: 'style: add wallet connection button styles' },
        ]
    },
    {
        name: 'feature/vite-config',
        prTitle: 'chore: add Vite configuration with React plugin',
        prBody: 'Creates the vite.config.js with the React plugin for JSX support, proxy configuration for the Stacks API during development, and build optimizations. Sets the dev server port to 3000.',
        commits: [
            { file: 'vite.config.js', mode: 'create', content: 'import { defineConfig } from \'vite\';\n', msg: 'chore: create vite config with defineConfig import' },
            { file: 'vite.config.js', mode: 'append', content: 'import react from \'@vitejs/plugin-react\';\n\n', msg: 'chore: import vite react plugin' },
            { file: 'vite.config.js', mode: 'append', content: 'export default defineConfig({\n  plugins: [react()],\n  server: {\n    port: 3000,\n    open: true,\n  },\n', msg: 'chore: configure vite dev server settings' },
            { file: 'vite.config.js', mode: 'append', content: '  build: {\n    outDir: \'dist\',\n    sourcemap: true,\n  },\n', msg: 'chore: configure vite build output settings' },
            { file: 'vite.config.js', mode: 'append', content: '  resolve: {\n    alias: {\n      \'@\': \'/src\',\n    },\n  },\n});\n', msg: 'chore: add path alias for src directory' },
        ]
    },
    {
        name: 'feature/index-html',
        prTitle: 'feat: create HTML entry point with meta tags',
        prBody: 'Adds the index.html entry point with proper meta tags for SEO, viewport configuration for responsive design, Google Fonts import for Inter, and the root div for React mounting.',
        commits: [
            { file: 'index.html', mode: 'create', content: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n', msg: 'feat: create index.html with doctype and meta tags' },
            { file: 'index.html', mode: 'append', content: '  <meta name="description" content="Tipjar - A decentralized tipping platform built on Stacks blockchain. Send STX tips to creators." />\n  <title>Tipjar - Decentralized Tipping on Stacks</title>\n', msg: 'feat: add SEO meta description and title' },
            { file: 'index.html', mode: 'append', content: '  <link rel="preconnect" href="https://fonts.googleapis.com" />\n  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />\n', msg: 'feat: import Google Fonts for Inter and JetBrains Mono' },
            { file: 'index.html', mode: 'append', content: '</head>\n<body>\n  <div id="root"></div>\n  <script type="module" src="/src/index.js"></script>\n</body>\n</html>\n', msg: 'feat: add root element and module script entry point' },
        ]
    },
];
