[project]
name = "tipjar"
description = "Decentralized tipping platform on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.tipjar]
path = "contracts/tipjar.clar"
clarity_version = 4
epoch = "3.3"

[contracts.tip-token]
path = "contracts/tip-token.clar"
clarity_version = 4
epoch = "3.3"

